-- Run once as ACCOUNTADMIN. Replace the temporary password before running.
USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS FACTORED_ANALYST;

CREATE WAREHOUSE IF NOT EXISTS FACTORED_WH
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE USER IF NOT EXISTS FACTORED_USER
  TYPE = PERSON
  PASSWORD = '<CHOOSE_A_STRONG_TEMPORARY_PASSWORD>'
  MUST_CHANGE_PASSWORD = TRUE
  DEFAULT_ROLE = FACTORED_ANALYST
  DEFAULT_WAREHOUSE = FACTORED_WH;

GRANT ROLE FACTORED_ANALYST TO USER FACTORED_USER;
GRANT USAGE ON WAREHOUSE FACTORED_WH TO ROLE FACTORED_ANALYST;
