-- Run after 00_account.sql, using ACCOUNTADMIN.
-- In Snowflake, replace <PATH_TO_CSV_ROOT>, <AWS_ACCESS_KEY_ID>, and
-- <AWS_SECRET_ACCESS_KEY> before running this script. Keep keys out of this file.
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE FACTORED_WH;

CREATE DATABASE IF NOT EXISTS FACTORED_ANALYTICS;
USE DATABASE FACTORED_ANALYTICS;
CREATE SCHEMA IF NOT EXISTS CORE;
CREATE SCHEMA IF NOT EXISTS ACTIVITY;
CREATE SCHEMA IF NOT EXISTS MARKETING;
CREATE SCHEMA IF NOT EXISTS SERVICE;

CREATE FILE FORMAT IF NOT EXISTS CORE.SOURCE_CSV
  TYPE = CSV
  COMPRESSION = AUTO
  FIELD_DELIMITER = ','
  FIELD_OPTIONALLY_ENCLOSED_BY = '0x22'
  SKIP_HEADER = 1
  MULTI_LINE = TRUE
  EMPTY_FIELD_AS_NULL = TRUE
  NULL_IF = ('')
  ENCODING = UTF8;

-- The URL must point to the S3 folder containing branches.csv, customers.csv,
-- and the partitioned dataset folders. For bucket root, remove
-- <PATH_TO_CSV_ROOT>/ so the URL ends immediately after the bucket name.
CREATE OR ALTER STAGE CORE.SOURCE_S3
  URL = 's3://factored-datathon-2026-s3-157725502942-us-east-2-an/<PATH_TO_CSV_ROOT>/'
  CREDENTIALS = (
    AWS_KEY_ID = '<AWS_ACCESS_KEY_ID>'
    AWS_SECRET_KEY = '<AWS_SECRET_ACCESS_KEY>'
  )
  FILE_FORMAT = (FORMAT_NAME = 'CORE.SOURCE_CSV');

CREATE TABLE IF NOT EXISTS CORE.BRANCHES (
  BRANCH_ID VARCHAR,
  BRANCH_CODE VARCHAR,
  BRANCH_NAME VARCHAR,
  BRANCH_TYPE VARCHAR,
  ADDRESS VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  COUNTRY VARCHAR,
  POSTAL_CODE VARCHAR,
  GEOGRAPHIC_ZONE VARCHAR,
  PHONE VARCHAR,
  EMAIL VARCHAR,
  OPENING_TIME VARCHAR,
  CLOSING_TIME VARCHAR,
  HAS_ATMS VARCHAR,
  ATM_COUNT VARCHAR,
  HAS_TELLER_WINDOWS VARCHAR,
  TELLER_WINDOW_COUNT VARCHAR,
  LATITUDE VARCHAR,
  LONGITUDE VARCHAR,
  BRANCH_OPENING_DATE VARCHAR,
  BRANCH_STATUS VARCHAR
);

CREATE TABLE IF NOT EXISTS SERVICE.CALL_CENTER_INTERACTIONS (
  INTERACTION_ID VARCHAR,
  INTERACTION_DATE VARCHAR,
  PROCESS_DATE VARCHAR,
  CUSTOMER_ID VARCHAR,
  AGENT_ID VARCHAR,
  INTERACTION_TYPE VARCHAR,
  CHANNEL VARCHAR,
  CONTACT_REASON VARCHAR,
  REASON_CATEGORY VARCHAR,
  DURATION_SECONDS VARCHAR,
  WAIT_TIME_SECONDS VARCHAR,
  WAS_RESOLVED VARCHAR,
  REQUIRES_FOLLOWUP VARCHAR,
  DETECTED_SENTIMENT VARCHAR,
  SENTIMENT_SCORE VARCHAR,
  CUSTOMER_DETECTED_ACCENT VARCHAR,
  AGENT_USED_ACCENT VARCHAR,
  WAS_ESCALATED VARCHAR,
  MENTIONED_PRODUCTS VARCHAR,
  HAS_TRANSCRIPT VARCHAR,
  HAS_RECORDING VARCHAR
);

CREATE TABLE IF NOT EXISTS SERVICE.CALL_TRANSCRIPTS (
  TRANSCRIPT_ID VARCHAR,
  INTERACTION_ID VARCHAR,
  PROCESS_DATE VARCHAR,
  CUSTOMER_ID VARCHAR,
  AGENT_ID VARCHAR,
  FULL_TEXT VARCHAR,
  CUSTOMER_TEXT VARCHAR,
  AGENT_TEXT VARCHAR,
  DETECTED_LANGUAGE VARCHAR,
  DETECTED_ACCENT VARCHAR,
  ACCENT_CONFIDENCE VARCHAR,
  DETECTED_KEYWORDS VARCHAR,
  MENTIONED_ENTITIES VARCHAR,
  DETECTED_INTENTS VARCHAR,
  MAIN_TOPICS VARCHAR,
  TRANSCRIPTION_MODEL VARCHAR,
  AUDIO_QUALITY VARCHAR,
  DURATION_SECONDS VARCHAR
);

CREATE TABLE IF NOT EXISTS MARKETING.CAMPAIGN_SENDS (
  SEND_ID VARCHAR,
  SEND_DATE VARCHAR,
  PROCESS_DATE VARCHAR,
  CAMPAIGN_ID VARCHAR,
  CUSTOMER_ID VARCHAR,
  SEND_CHANNEL VARCHAR,
  TEMPLATE_USED VARCHAR,
  SUBJECT VARCHAR,
  SEND_STATUS VARCHAR,
  WAS_DELIVERED VARCHAR,
  WAS_OPENED VARCHAR,
  OPEN_DATE VARCHAR,
  WAS_CLICKED VARCHAR,
  CLICK_DATE VARCHAR,
  CLICK_COUNT VARCHAR,
  HAD_CONVERSION VARCHAR,
  CONVERSION_DATE VARCHAR,
  CONVERSION_VALUE VARCHAR,
  OPEN_DEVICE VARCHAR,
  OPEN_COUNTRY VARCHAR,
  FAILURE_REASON VARCHAR,
  SEND_COST VARCHAR
);

CREATE TABLE IF NOT EXISTS SERVICE.COMPLAINTS (
  COMPLAINT_ID VARCHAR,
  CREATION_DATE VARCHAR,
  PROCESS_DATE VARCHAR,
  CUSTOMER_ID VARCHAR,
  CASE_TYPE VARCHAR,
  CATEGORY VARCHAR,
  SUBCATEGORY VARCHAR,
  RECEPTION_CHANNEL VARCHAR,
  AFFECTED_PRODUCT_ID VARCHAR,
  RELATED_BRANCH_ID VARCHAR,
  ORIGIN_INTERACTION_ID VARCHAR,
  DESCRIPTION VARCHAR,
  CLAIMED_AMOUNT VARCHAR,
  CURRENCY VARCHAR,
  PRIORITY VARCHAR,
  STATUS VARCHAR,
  ASSIGNED_AGENT_ID VARCHAR,
  ASSIGNMENT_DATE VARCHAR,
  FIRST_RESPONSE_DATE VARCHAR,
  RESOLUTION_DATE VARCHAR,
  CLOSING_DATE VARCHAR,
  SLA_BREACHED VARCHAR,
  RESOLUTION_DAYS VARCHAR,
  RESOLUTION VARCHAR,
  COMPENSATION_GRANTED VARCHAR,
  RESOLUTION_SATISFACTION VARCHAR,
  IS_REPEAT_COMPLAINER VARCHAR
);

CREATE TABLE IF NOT EXISTS CORE.CUSTOMERS (
  CUSTOMER_ID VARCHAR,
  DOCUMENT_NUMBER VARCHAR,
  DOCUMENT_TYPE VARCHAR,
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR,
  DATE_OF_BIRTH VARCHAR,
  GENDER VARCHAR,
  EMAIL VARCHAR,
  MOBILE_PHONE VARCHAR,
  LANDLINE_PHONE VARCHAR,
  ADDRESS VARCHAR,
  CITY VARCHAR,
  STATE VARCHAR,
  COUNTRY VARCHAR,
  POSTAL_CODE VARCHAR,
  DETECTED_ACCENT VARCHAR,
  SEGMENT VARCHAR,
  CREDIT_SCORE VARCHAR,
  ESTIMATED_MONTHLY_INCOME VARCHAR,
  OCCUPATION VARCHAR,
  MARITAL_STATUS VARCHAR,
  EDUCATION_LEVEL VARCHAR,
  REGISTRATION_DATE VARCHAR,
  REGISTRATION_BRANCH_ID VARCHAR,
  CUSTOMER_STATUS VARCHAR,
  LAST_UPDATED VARCHAR,
  ACCEPTS_MARKETING VARCHAR
);

CREATE TABLE IF NOT EXISTS CORE.DAILY_EXCHANGE_RATES (
  DATE VARCHAR,
  SOURCE_CURRENCY VARCHAR,
  TARGET_CURRENCY VARCHAR,
  EXCHANGE_RATE VARCHAR,
  BUY_RATE VARCHAR,
  SELL_RATE VARCHAR,
  SOURCE VARCHAR
);

CREATE TABLE IF NOT EXISTS ACTIVITY.DIGITAL_EVENTS (
  EVENT_ID VARCHAR,
  EVENT_DATE VARCHAR,
  PROCESS_DATE VARCHAR,
  CUSTOMER_ID VARCHAR,
  SESSION_ID VARCHAR,
  EVENT_TYPE VARCHAR,
  EVENT_CATEGORY VARCHAR,
  CHANNEL VARCHAR,
  PLATFORM VARCHAR,
  BROWSER VARCHAR,
  APP_VERSION VARCHAR,
  PAGE_URL VARCHAR,
  PAGE_TITLE VARCHAR,
  ACTION VARCHAR,
  ELEMENT_ID VARCHAR,
  PRODUCT_ID VARCHAR,
  EVENT_VALUE VARCHAR,
  DURATION_SECONDS VARCHAR,
  IP_ADDRESS VARCHAR,
  IP_COUNTRY VARCHAR,
  IP_CITY VARCHAR,
  IS_MOBILE VARCHAR,
  REFERRER VARCHAR,
  UTM_SOURCE VARCHAR,
  UTM_MEDIUM VARCHAR,
  UTM_CAMPAIGN VARCHAR
);

CREATE TABLE IF NOT EXISTS MARKETING.MARKETING_CAMPAIGNS (
  CAMPAIGN_ID VARCHAR,
  CAMPAIGN_NAME VARCHAR,
  DESCRIPTION VARCHAR,
  CAMPAIGN_TYPE VARCHAR,
  CAMPAIGN_OBJECTIVE VARCHAR,
  PROMOTED_PRODUCT VARCHAR,
  TARGET_SEGMENT VARCHAR,
  TARGET_COUNTRY VARCHAR,
  START_DATE VARCHAR,
  END_DATE VARCHAR,
  BUDGET VARCHAR,
  CAMPAIGN_STATUS VARCHAR,
  EXPECTED_CONVERSION_RATE VARCHAR
);

CREATE TABLE IF NOT EXISTS CORE.PRODUCTS (
  PRODUCT_ID VARCHAR,
  CUSTOMER_ID VARCHAR,
  PRODUCT_TYPE VARCHAR,
  PRODUCT_NUMBER VARCHAR,
  CURRENCY VARCHAR,
  CURRENT_BALANCE VARCHAR,
  CREDIT_LIMIT VARCHAR,
  INTEREST_RATE VARCHAR,
  OPENING_DATE VARCHAR,
  EXPIRATION_DATE VARCHAR,
  OPENING_BRANCH_ID VARCHAR,
  PRODUCT_STATUS VARCHAR,
  OPENING_CHANNEL VARCHAR,
  HAS_LINKED_APP VARCHAR,
  DAYS_PAST_DUE VARCHAR,
  LAST_TRANSACTION_DATE VARCHAR,
  LAST_UPDATED VARCHAR
);

CREATE TABLE IF NOT EXISTS SERVICE.SATISFACTION_SURVEYS (
  SURVEY_ID VARCHAR,
  SURVEY_DATE VARCHAR,
  PROCESS_DATE VARCHAR,
  INTERACTION_ID VARCHAR,
  CUSTOMER_ID VARCHAR,
  AGENT_ID VARCHAR,
  SURVEY_TYPE VARCHAR,
  SEND_CHANNEL VARCHAR,
  MAIN_SCORE VARCHAR,
  NPS_CATEGORY VARCHAR,
  QUESTION_1_TEXT VARCHAR,
  QUESTION_1_RESPONSE VARCHAR,
  QUESTION_2_TEXT VARCHAR,
  QUESTION_2_RESPONSE VARCHAR,
  QUESTION_3_TEXT VARCHAR,
  QUESTION_3_RESPONSE VARCHAR,
  OPEN_COMMENTS VARCHAR,
  COMMENT_SENTIMENT VARCHAR,
  RESPONSE_TIME_HOURS VARCHAR,
  CAMPAIGN_RESPONSE_RATE VARCHAR
);

CREATE TABLE IF NOT EXISTS SERVICE.SERVICE_AGENTS (
  AGENT_ID VARCHAR,
  EMPLOYEE_CODE VARCHAR,
  FIRST_NAME VARCHAR,
  LAST_NAME VARCHAR,
  EMAIL VARCHAR,
  PHONE VARCHAR,
  NATIVE_ACCENT VARCHAR,
  COUNTRY_OF_ORIGIN VARCHAR,
  ASSIGNED_BRANCH_ID VARCHAR,
  AGENT_TYPE VARCHAR,
  EXPERIENCE_LEVEL VARCHAR,
  LANGUAGES VARCHAR,
  SPECIALTY VARCHAR,
  HIRE_DATE VARCHAR,
  AVG_CSAT VARCHAR,
  TOTAL_MONTHLY_INTERACTIONS VARCHAR,
  AGENT_STATUS VARCHAR,
  WORK_SHIFT VARCHAR
);

CREATE TABLE IF NOT EXISTS ACTIVITY.TRANSACTIONS (
  TRANSACTION_ID VARCHAR,
  TRANSACTION_DATE VARCHAR,
  PROCESS_DATE VARCHAR,
  PRODUCT_ID VARCHAR,
  CUSTOMER_ID VARCHAR,
  TRANSACTION_TYPE VARCHAR,
  TRANSACTION_CATEGORY VARCHAR,
  AMOUNT VARCHAR,
  CURRENCY VARCHAR,
  AMOUNT_USD VARCHAR,
  CHANNEL VARCHAR,
  BRANCH_ID VARCHAR,
  MERCHANT_NAME VARCHAR,
  MERCHANT_CATEGORY VARCHAR,
  TRANSACTION_COUNTRY VARCHAR,
  TRANSACTION_CITY VARCHAR,
  TRANSACTION_STATUS VARCHAR,
  RESPONSE_CODE VARCHAR,
  IS_FRAUD VARCHAR,
  FRAUD_SCORE VARCHAR,
  LATITUDE VARCHAR,
  LONGITUDE VARCHAR
);

-- Let FACTORED_USER query the tables and run the COPY commands in 02_load.sql.
GRANT USAGE ON DATABASE FACTORED_ANALYTICS TO ROLE FACTORED_ANALYST;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FACTORED_ANALYTICS TO ROLE FACTORED_ANALYST;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE FACTORED_ANALYTICS TO ROLE FACTORED_ANALYST;
GRANT SELECT, INSERT ON ALL TABLES IN DATABASE FACTORED_ANALYTICS TO ROLE FACTORED_ANALYST;
GRANT SELECT, INSERT ON FUTURE TABLES IN DATABASE FACTORED_ANALYTICS TO ROLE FACTORED_ANALYST;
GRANT USAGE ON FILE FORMAT CORE.SOURCE_CSV TO ROLE FACTORED_ANALYST;
GRANT USAGE ON STAGE CORE.SOURCE_S3 TO ROLE FACTORED_ANALYST;
