-- Run after 01_setup.sql and after confirming access to the S3 stage.
-- Connect as FACTORED_USER or activate FACTORED_ANALYST.
USE ROLE FACTORED_ANALYST;
USE WAREHOUSE FACTORED_WH;
USE DATABASE FACTORED_ANALYTICS;
-- Confirm access before loading: LIST @CORE.SOURCE_S3;
COPY INTO CORE.BRANCHES
  FROM @CORE.SOURCE_S3/branches.csv
  ON_ERROR = ABORT_STATEMENT;
COPY INTO SERVICE.CALL_CENTER_INTERACTIONS
  FROM @CORE.SOURCE_S3/call_center_interactions/
  PATTERN = '.*[.]csv'
  ON_ERROR = ABORT_STATEMENT;
COPY INTO SERVICE.CALL_TRANSCRIPTS
  FROM @CORE.SOURCE_S3/call_transcripts/
  PATTERN = '.*[.]csv'
  ON_ERROR = ABORT_STATEMENT;
COPY INTO MARKETING.CAMPAIGN_SENDS
  FROM @CORE.SOURCE_S3/campaign_sends/
  PATTERN = '.*[.]csv'
  ON_ERROR = ABORT_STATEMENT;
COPY INTO SERVICE.COMPLAINTS
  FROM @CORE.SOURCE_S3/complaints/
  PATTERN = '.*[.]csv'
  ON_ERROR = ABORT_STATEMENT;
COPY INTO CORE.CUSTOMERS
  FROM @CORE.SOURCE_S3/customers.csv
  ON_ERROR = ABORT_STATEMENT;
COPY INTO CORE.DAILY_EXCHANGE_RATES
  FROM @CORE.SOURCE_S3/daily_exchange_rates.csv
  ON_ERROR = ABORT_STATEMENT;
COPY INTO ACTIVITY.DIGITAL_EVENTS
  FROM @CORE.SOURCE_S3/digital_events/
  PATTERN = '.*[.]csv'
  ON_ERROR = ABORT_STATEMENT;
COPY INTO MARKETING.MARKETING_CAMPAIGNS
  FROM @CORE.SOURCE_S3/marketing_campaigns.csv
  ON_ERROR = ABORT_STATEMENT;
COPY INTO CORE.PRODUCTS
  FROM @CORE.SOURCE_S3/products.csv
  ON_ERROR = ABORT_STATEMENT;
COPY INTO SERVICE.SATISFACTION_SURVEYS
  FROM @CORE.SOURCE_S3/satisfaction_surveys/
  PATTERN = '.*[.]csv'
  ON_ERROR = ABORT_STATEMENT;
COPY INTO SERVICE.SERVICE_AGENTS
  FROM @CORE.SOURCE_S3/service_agents.csv
  ON_ERROR = ABORT_STATEMENT;
COPY INTO ACTIVITY.TRANSACTIONS
  FROM @CORE.SOURCE_S3/transactions/
  PATTERN = '.*[.]csv'
  ON_ERROR = ABORT_STATEMENT;
